import { NextAuthProvider } from "./Provider";
import { GenerateIconProvider } from "../context/GenerateIconContext";
import "./globals.css";
import Navbar from "../components/shared/Navbar";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IconCraftAI - Generate icons with AI",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <NextAuthProvider>
          <GenerateIconProvider>
            <Navbar />
            <main>{children}</main>
          </GenerateIconProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
