import { NextAuthProvider } from "./Provider";
import Navbar from "./components/shared/Navbar";
import { GenerateIconProvider } from "./context/GenerateIconContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <GenerateIconProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextAuthProvider>
            <Navbar />
            {children}
          </NextAuthProvider>
        </body>
      </html>
    </GenerateIconProvider>
  );
};

export default RootLayout;
